### ISSUE TITLE
Hi, I'm very interested in your research. May I ask when your code will be updated?

### ISSUE THREAD

**Issue by Raywoo1** [gbarbarani/re-ranking-for-VPR#2]

**Comment by gbarbarani** [comment]
Cosplace ResNet50 base predictions have been added to the outputs folder. All the configurations present in benchmark.sh have been tested, you can look at the bash script for an example of configurations and input/outputs allowed. The complete benchmark results and the validation framework will be added in the next months. Let me know if you find the library lacking a necessary feature.

**Comment by MAX-OTW** [comment]
Hello, @gbarbarani @ZerothB @gmberton ,-I really appreciate for your "re-ranking-for-VPR" work！Congratulations :)
I need your help with following question：
I noticed that there are also DELG+RANSAC, DELG+RRT methods in the paper, but these parts are not found in the benchmark.sh,is it convenient to provide relevant codes?Or are these two parts(DELG+RANSAC, DELG+RRT) difficult to integrate into the existing code repository?

I am always looking forward to your kind response.
Best regards.

**Comment by gbarbarani** [comment]
Hi @MAX-OTW,

We're facing significant challenges integrating DELG into our system. Currently, we've employed custom scripts to execute it on relevant image pairs. These scripts, being ad hoc, heavily rely on the DELG API. Currently, there are no plans to release them in their current form. However, we are considering integrating a DELG Mock API to enable the use of additional features following the extraction of DELG local and global descriptors within the next three months.
